version: "3.9"
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"